### ISSUE TITLE
[QUESTION] - how about drag and drop for the creditor? 

### ISSUE THREAD

**Issue by seoyoon-jin221** [cs130-w21/dots-ios#101]
## Description
To select a creditor, you have to hold on to it. How about drag and drop so it's more intuitive for the user?

**Comment by JackZhao98** [comment]
That was our original design, but not implemented, because:
* Drag and drop gesture increases extra finger movement, unnecessary labor for users
* The original dots were designed to be placed around the creditor part, like a circular shape, which looked natural if we have drag and drop; but the current design is to have all the dots in a horizontal scroll view, drag no longer seems natural
* Dragging a dot and dragging the sheet view (up and down) conflicts, I wish to keep the original sheet view gesture design.

How do you think? 
Thanks for the suggestion LOL : )
